//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFiles", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GeusData {
            get {
                object obj = ResourceManager.GetObject("GeusData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year,Month,Day,Hour,Min,Second,North,East,Depth(km),Richter tal
        ///2017,3,7,14,47,9.7,57761,15001,4.6,2.6
        ///2017,3,6,22,17,40.7,58041,8215,36.9,2.1
        ///2017,3,6,13,2,2.8,56367,13228,0.0,2.4
        ///2017,3,6,12,26,20.1,55662,13382,0.0,2.1
        ///2017,3,3,13,34,58.4,57265,15736,0.0,2.5
        ///2017,3,3,11,3,19.1,55659,13343,2.2,2.5
        ///2017,3,2,16,26,49.5,56128,12434,28.7,2.6
        ///2017,2,23,16,59,0.3,58104,5552,6.4,1.8
        ///2017,2,23,14,13,9.2,58581,5551,8.2,2.0
        ///2017,2,23,13,49,25.3,57488,12563,9.2,1.3
        ///2017,2,23,12,37,14.0,57426,14788,0.0,0.8        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeussDataTable {
            get {
                return ResourceManager.GetString("GeussDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GeussDataTable1 {
            get {
                object obj = ResourceManager.GetObject("GeussDataTable1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&quot;1&quot;&gt;
        ///	&lt;tbody&gt;
        ///		&lt;tr valign=&quot;top&quot;&gt;
        ///			&lt;th width=&quot;32&quot;&gt; y &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt; m &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt; d &lt;/th&gt;
        ///			&lt;th width=&quot;12&quot;&gt; &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt; h &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt; m &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt; s &lt;/th&gt;
        ///			&lt;th width=&quot;12&quot;&gt; &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt;Nord&lt;/th&gt;
        ///			&lt;th width=&quot;12&quot;&gt; &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt;Øst&lt;/th&gt;
        ///			&lt;th width=&quot;12&quot;&gt; &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt;dybde [km]&lt;/th&gt;
        ///			&lt;th width=&quot;12&quot;&gt; &lt;/th&gt;
        ///			&lt;th width=&quot;32&quot;&gt;Richter tal&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr valign=&quot;top&quot;&gt;
        ///			&lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeussHtmlTable {
            get {
                return ResourceManager.GetString("GeussHtmlTable", resourceCulture);
            }
        }
    }
}
